// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    return formContainer.on('form_loaded', function(e) {
      $('textarea.code', formContainer).each(function() {
        var editor;
        editor = CodeMirror.fromTextArea(this, {
          lineNumbers: true,
          lineWrapping: true,
          autofocus: true,
          mode: 'php',
          theme: 'monokai',
          tabSize: 4,
          indentUnit: 4,
          indentWithTabs: true,
          autoCloseTags: true,
          tabMode: "indent"
        });
        return $(this).data('editor', editor);
      });
      return $('[type="submit"]', formContainer).click(function() {
        return $('textarea.code', formContainer).each(function() {
          var editor;
          editor = $(this).data('editor');
          if (!editor) {
            return;
          }
          $(this).val(editor.getValue());
          return editor = null;
        });
      });
    });
  });

}).call(this);
