// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    return formContainer.on('form_loaded', function(e) {
      $('textarea.code', formContainer).each(function() {
        var editor;
        editor = CodeMirror.fromTextArea(this, {
          lineNumbers: true,
          lineWrapping: true,
          autofocus: true,
          mode: 'php',
          theme: 'monokai',
          tabSize: 4,
          indentUnit: 4,
          indentWithTabs: true,
          autoCloseTags: true,
          tabMode: "indent"
        });
        return $(this).data('editor', editor);
      });
      $('.nav-tabs', formContainer).on('shown', function(e) {
        var codeMirror, editor;
        editor = $('div.tab-pane.active textarea.code').data('editor');
        codeMirror = $('div.tab-pane.active .CodeMirror');
        return editor != null ? editor.setSize(codeMirror.width(), codeMirror.height()) : void 0;
      });
      return $('[type="submit"]', formContainer).click(function() {
        return $('textarea.code', formContainer).each(function() {
          var editor;
          editor = $(this).data('editor');
          editor.save();
          return editor = null;
        });
      });
    });
  });

}).call(this);
