// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    return formContainer.on('form_loaded', function(e) {
      return $('textarea.code', formContainer).each(function() {
        return CodeMirror.fromTextArea(this, {
          lineNumbers: true,
          lineWrapping: true,
          autofocus: true,
          mode: 'php',
          theme: 'monokai',
          tabSize: 4,
          indentUnit: 4,
          indentWithTabs: true,
          autoCloseTags: true
        });
      });
    });
  });

}).call(this);
