// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    $('body .container').on('click', '.cke_contents a', function(e) {
      e.stopImmediatePropagation();
      e.preventDefault();
      return e.stopPropagation();
    });
    return formContainer.on('form_loaded', function(e) {
      $('textarea.editor', formContainer).each(function() {
        var editor;
        editor = CKEDITOR.replace(this, {
          language: 'ru'
        });
        return $(this).data('editor', editor);
      });
      return $('[type="submit"]', formContainer).click(function() {
        return $('textarea.editor', formContainer).each(function() {
          var editor;
          editor = $(this).data('editor');
          if (editor != null) {
            editor.destroy();
          }
          $('.nav-tabs', formContainer).off('shown');
          return editor = null;
        });
      });
    });
  });

}).call(this);
